Repository HongJungKim-dev/sidedish, pull requests merged in 2022-04, with the labels that each got.

#3 [feat] 헤더 구현
  package-lock.json
  package.json
  public/assets/arrowLeft.png
  public/assets/arrowRight.png
  public/assets/basket.png
  public/assets/minus.png
  public/assets/plus.png
  public/assets/search.png
  public/assets/user.png
  src/App.js
  src/Header.js
  src/css/mixins.js
  src/css/variables.js
  src/index.js
Labels: feat, FE

#4 [feat] 메인 카드 데이터 요청
  .prettierrc
  public/data/mainCard.json
  public/data/mainDish.json
  public/data/sideDish.json
  public/data/soup.json
  public/index.html
  src/App.js
  src/Header.js
  src/MainCard.js
  src/css/mixins.js
  src/css/variables.js
  src/index.js
  src/utility/util.js
Labels: feat, FE

#5 [fix] useEffect내의 함수 분리, 의존성 배열 수정
  src/App.js
  src/MainCard.js
Labels: feat, FE

#6 [feat] 헤더 hover시에 border선 내리기
  src/Header.js
  src/css/mixins.js
Labels: feat, FE

#7 [refactor] #1 리뷰반영 (header 부분)
  public/data/mainCard.json
  public/data/sideDish.json
  public/data/soup.json
  src/Header.js
  src/components/Gnb.js
  src/components/GnbItem.js
  src/components/Menu.js
Labels: refactor, FE

#8 [feat] 메인 카드 탭에 따라 렌더링
  public/data/mainCard.json
  src/App.js
  src/MainCard.js
  src/SubCard.js
  src/components/Card.js
  src/components/CategoryTitle.js
  src/components/Infos.js
  src/components/Tab.js
  src/container/CardContainer.js
Labels: feat, FE

#9 feat: silde버튼 추가 및 margin-left 변경
  src/App.js
  src/Header.js
  src/MainCard.js
  src/SubCard.js
  src/components/Button.js
  src/components/Card.js
  src/components/CategoryTitle.js
  src/components/Gnb.js
  src/components/Menu.js
  src/components/Tab.js
  src/container/CardContainer.js
  src/css/variables.js
  src/index.js
Labels: feat, FE

#11 feat: 이미지 크기 자동조절 및 더보기 버튼 클릭 이벤트 핸들
  public/data/mainCard.json
  public/data/mainDish.json
  src/App.js
  src/SubCard.js
  src/components/Button.js
  src/components/Card.js
  src/components/Tab.js
  src/container/CardContainer.js
  src/css/variables.js
Labels: feat, FE

#12 refactor: fetch 에러 처리
  public/index.html
  src/App.js
  src/components/Card.js
Labels: feat, FE

#16 feat: 버튼 클릭시 슬라이드 구현
  public/data/mainDish.json
  src/Header.js
  src/MainCard.js
  src/SubCard.js
  src/components/Button.js
  src/components/Card.js
  src/components/CardBox.js
  src/components/CategoryTitle.js
  src/components/Tab.js
  src/container/CardContainer.js
Labels: feat, FE

#19 [PR] STEP3 PR 반영
  src/App.js
  src/MainCard.js
  src/SubCard.js
  src/components/Button.js
  src/components/Card.js
  src/components/CardBox.js
  src/components/Slider.js
  src/components/Tab.js
  src/container/CardContainer.js
Labels: FE, PR

#22 refactor: react 최적화 및 sidedish css 작업
  public/data/mainDish.json
  src/App.js
  src/Header.js
  src/MainCard.js
  src/SubCard.js
  src/components/Card.js
  src/components/CardBox.js
  src/components/CardOrderPage.js
  src/components/CategoryTitle.js
  src/components/Infos.js
  src/components/Modal.js
  src/container/CardContainer.js
  src/css/mixins.js
  src/css/variables.js
Labels: refactor, FE
